- .appveyor.yml
I managed to setup Windows in a virtual machine, but the test failures are weird.
For now, let's just disable the automatic tests on Python 3.5 and keep PR #11 open for me to play around.
> CI: Disable Python 3.5 on Windows for now.

- README.md
- mnemosyne/pyqt_ui/review_wdgt.py
- mnemosyne/pyqt_ui/review_wdgt.ui
- Disables the context menu in the review widget.
- I got sidetracked: tiny change to `review_wdgt.ui` that promotes the buttons correctly so they are displayed in the designer. Not sure if this is worth the change.
It is in general possible to create your own context menu (see [here](https://github.com/three-comrades/mnemosyne/commit/601aa1fe1f66a841aba5d98af8a14f3c5d2a4ac1)), but I totally missed that `ctrl+e` already let's me edit the current card. I don't think it makes much sense to replicate that in the context menu, so for now let's just disable it completely.
Edit: oops, had to rebase on master.
> Disable context menu.

- .appveyor.yml
An HTTP GET request for the current URL will return an HTTP 404. This
breaks AppVeyor CI.
> Fix URL to miktex-portable.exe

- TODO
other changes should be caused by github editor upgrading windows-1252 encoding to UTF-8 (if it is unwanted I may resubmit PR with only interger->integer change once I have access to my PC)
> interger -> integer

- mnemosyne/android/build.gradle
Such settings should be set in local.properties and not committed to the git repo.
Fixes #84.
Please merge #91 first so that #84 can actually be marked as fixed ;)
> Remove the non-portable settings buildDir from build.gradle

- mnemosyne/libmnemosyne/file_formats/tsv.py
This fixes an issues that causes UTF-8 characters in TSV files on macOS
to fail the import process
Issue report at
https://groups.google.com/d/msgid/mnemosyne-proj-users/3930acc4-c703-4944-852a-fcc6fdcb1339%40googlegroups.com
> Remove debugging print statement from tsv import code

- README.md
- mnemosyne/libmnemosyne/controllers/default_controller.py
- mnemosyne/libmnemosyne/databases/SQLite.py
- mnemosyne/libmnemosyne/databases/SQLite_logging.py
- mnemosyne/libmnemosyne/logger.py
- mnemosyne/libmnemosyne/loggers/database_logger.py
- mnemosyne/libmnemosyne/schedulers/SM2_mnemosyne.py
- openSM2sync/log_entry.py
- tests/test_controller.py
- tests/test_database.py
- tests/test_logging.py
- tests/test_scheduler.py
When we close the Mnemosyne application and re-open it, it won't
remember the number of the already memorized cards. In other words, it
won't warn you if you've already learned 15 or more words.
This PR aims to fix this issue and re-construct the
`self._fact_ids_memorised` from the logs which are not that hard.
We can fetch all the newly learned cards (same query as in the statistics) and all the forgotten but
learned cards today. Combining the two, we can get the number of learned cards today.
- The already memorized cards are re-constructed from the logs
- It only warns once per day
- Fixed long-time flaky python3.7 test
Any comments are welcome.
> Remember how many cards we've learned today even after re-opening the app

- mnemosyne/libmnemosyne/configuration.py
- tests/test_configuration.py
The users might want to use their own system language as the Mnemosyne language by default. Currently, the only default language is English.
We could rely on the built-in `locale` and its `getdefaultlocale()` function which can show the system language. the `getdefaultlocale()` is platform independent and working on all platforms.
If there is no supported language, we are going to default it to English just like as it was before.
> Set system language as the default language fixes #42

- mnemosyne/libmnemosyne/file_formats/mnemosyne1.py
- mnemosyne/libmnemosyne/scheduler.py
- mnemosyne/libmnemosyne/schedulers/SM2_mnemosyne.py
Move midnight_UTC from SM2 to base Scheduler since it is
not specific to SM2, and remove the redundant midnight_UTC
implementation elsewhere
(This is partly to test the waters for future patches to
move some non-SM2 specific bits into the base Scheduler
class, like the interval_string functions)
> Move midnight_UTC from SM2 to base Scheduler

- tests/test_statistics.py
Some tests fail in EST depending on the system time (after 7pm
at least). Setting to UTC fixes it for me but I didn't investigate
further
> tests: More usage of UTC timezone

- .mailmap
- mnemosyne/libmnemosyne/scheduler.py
- mnemosyne/libmnemosyne/schedulers/SM2_mnemosyne.py
- tests/test_statistics.py
Move more non-SM2 specific functions to the base Scheduler class,
mostly those dealing with time and dates.
Moving these to the base class makes it explicit they are public
APIs, and it makes it easier to review the specific logic of
the SM2 scheduler
> Move more functions to Scheduler()

- mnemosyne/libmnemosyne/__init__.py
- mnemosyne/libmnemosyne/ui_components/main_widget.py
- mnemosyne/pyqt_ui/main_wdgt.py
Presently, ctrl-c/KeyboardInterrupt will print an uncaught exception
dialog, which seems suboptimal.
In the excepthook, call a new public MainWidget API,
handle_keyboard_interrupt. Make the QT frontend exit the app in this
case after saving state
> Exit app on ctrl-c

- mnemosyne/pyqt_ui/review_wdgt.py
On the linux console, mnemosyne repeatedly prints:
QIODevice::read (QProcess): device not open
This is due to trying to interact with the 'mplayer' process
regardless of whether it's running or not. Check the process state
before trying to interact with it.
I don't have any flashcards that use the mplayer integration, so
I didn't test that this doesn't cause any unwanted issues
> Fix qprocess warnings

- README.md
fixes #146 and moves info not specific to this repository (git and github tutorial) to the bottom
also some minor rearrangement - add newline to use list formatting supported by more markdown flavors, moves info about download location before section titled "Installation of the development version and hacking"
this PR should not break windows newlines (I applied `unix2dos` newline rewritting)
> Rearrange README.md

- README.md
were working in retext, I failed to check whatever Github accepts them
Sorry for not checking properly, this time I looked at https://github.com/matkoniecz/mnemosyne/blob/5ffa207f1239392f614fd2d9a184e168c35b0f33/README.md#installation-of-the-development-version-and-hacking
> fix section linking that I broke

- mnemosyne/libmnemosyne/configuration.py
- mnemosyne/libmnemosyne/filters/latex.py
This approach makes config.py behave the same as Windows/Linux, but adds the two known paths for LaTeX that I've seen users use to the path manually. That means either approach will work out of the box
> more reliable way to retrieve LaTeX path for macOS

- .gitattributes
Follow-up on #174 
This does two things:
- A fresh check out of this repository will always result in `\n` line endings for `mnemosyne/pyqt_ui/mnemosyne` locally - even on Windows.
- The file will always be committed with `\n` line endings.
But if you change the line endings in your local file, they won't be changed back. I don't think it's possible to enforce this. It just will always normalize the line endings in the file when committing/saving.
> Force lf line ending for the executable.

- mnemosyne/web_server/web_server.py
Do not access ReleaseDatabaseAfterTimeout if the database is not loaded.
When both the web-server and sync server are started, the database
might not be loaded because it operates on the "release_database".
```python
if not self.is_mnemosyne_loaded and filename != "/release_database":
self.load_mnemosyne()
self.release_database_after_timeout.ping()
#^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ is not defined if filename = "/release_database"
```
AttributeError("'WebServerThread' object has no attribute 'release_database_after_timeout'")
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/cheroot/server.py", line 1280, in communicate
req.respond()
File "/usr/local/lib/python3.8/site-packages/cheroot/server.py", line 1083, in respond
self.server.gateway(self).respond()
File …
> Fix No attribute `release_database_after_timeout`

- mnemosyne/pyqt_ui/mnemosyne
This allows window managers to figure out to which desktop entry the Mnemosyne process belongs. I’ve found this to be necessary for the application name and icon to be displayed correctly in some places on Wayland. I guess it’s because Mnemosyne is running in the python interpreter rather than its own executable.
Before:
After:
> Associate Mnemosyne with its desktop entry

- tests/test_cloze.py
> Remove math mode commands in non-math mode <latex> tag in cloze test

- README
- README.md
- mnemosyne/android/.idea/checkstyle-idea.xml
- mnemosyne/android/.idea/misc.xml
- mnemosyne/android/.idea/modules.xml
- mnemosyne/android/android.iml
- mnemosyne/android/app/src/main/java/org/mnemosyne/MnemosyneActivity.java
- mnemosyne/android/app/src/main/java/org/mnemosyne/MnemosyneBridge.java
- mnemosyne/android/app/src/main/java/org/mnemosyne/MnemosyneThread.java
- mnemosyne/android/app/src/main/java/org/mnemosyne/SyncActivity.java
- mnemosyne/android/app/src/main/res/layout/sync.xml
- mnemosyne/android_python/configuration.py
- mnemosyne/libmnemosyne/configuration.py
- mnemosyne/libmnemosyne/sync_server.py
- mnemosyne/pyqt_ui/configuration.py
- mnemosyne/pyqt_ui/configuration_wdgt_servers.py
- mnemosyne/pyqt_ui/configuration_wdgt_servers.ui
- mnemosyne/pyqt_ui/sync_dlg.py
- mnemosyne/pyqt_ui/sync_dlg.ui
- requirements.txt
This PR contains two (relatively) small changes to avoid storing passwords in plaintext in the sync mechanism:
- On the server side, only a hash value of the password will be stored. I was actually quite shocked to learn that Mnemosyne didn’t do this already. The password hashing algorithms recommended most often these days are Argon2, bcrypt and scrypt<sup>[Citation needed]</sup>, but unfortunately none of them are universally available in the Python standard library, so I used the fairly lightweight argon2-cffi library to implement hashing using Argon2. I wrote the code in such a way that the library is only required for frontends that actually make use of the sync server (e.g. the Android frontend does not require the library). Pre-existing plaintext passwords will be hashed …
> Sync password handling enhancements

- README
Mnemosyne would not start after installing it from sources on a fresh install of Python on a Fedora 34 distro.
Installing "PyQtWebEngine" solved the issue.
> Added "PyQtWebEngine" to the pip install/upgrade command.

- mnemosyne/pyqt_ui/qtextedit2.py
Hello~ the python3 pillow module now supports .webp format so I would like to update the filename filters to include .webp
I tested this on Ubuntu 20.04.3 LTS where Python 3.8.10 is the default python 3 version and inserting .webp images into Mnemosyne cards is working fine. I am replacing the animated .gif files in my mnemosyne cards with animated .webp files which are about 40% smaller!
> add .webp to insert_img() filter as PIL now supports webp

- mnemosyne/libmnemosyne/__init__.py
see https://github.com/mnemosyne-proj/mnemosyne/issues/200#issuecomment-916293360
sadly the warnings get printed twice:
```
/home/lukas/git/mnemosyne/mnemosyne/libmnemosyne/__init__.py:370: UserWarning: gTTS package is not installed. Text to speak feature will not be available 
warnings.warn("gTTS package is not installed. Text to speak feature will not be available ")
```
> add warnings for missing gtts and google_trans

- mnemosyne/libmnemosyne/renderers/anki_renderer.py
I'm not sure exactly why this happened, but I tried changing a front-to-back card to the "Cloze" card type. When I restarted Mnemosyne and opened the card browser, it went into an infinite loop complaining that the field `ord` of the card's `extra_data` dict was missing.
Using a default value of the empty string also results in an infinite error loop, since some arithmetic is performed on the value later. I'm not sure where the "ord" field is supposed to come from, so for now I set it to a default value of `0` but that produces empty output in the card preview. It does stop the infinite error though.
> Avoid infinite error loop when converting a card to cloze type

- requirements.txt
Checking out `41fd12ab731ef323502c0209665917ac8ec13763` and building in a venv by doing the following:
```
pip install -r requirements.txt
make build-all-deps
make
```
Would fail on `make` with the error:
```
Traceback (innermost last):
File "/home/hgrahamcs/workspace/mnemosyne/mnemosyne/pyqt_ui/mnemosyne", line 150, in <module>
from PyQt5 import QtWebEngineWidgets  # Needs to happen first for some reason.
ImportError: cannot import name 'QtWebEngineWidgets' from 'PyQt5' (/home/hgrahamcs/workspace/mnemosyne/venv/lib64/python3.10/site-packages/PyQt5/__init__.py)
make: *** [makefile:32: run] Error 1
```
To resolve this error I had to add `pyqtwebengine` to the requirements.txt file.
> Added pyqtwebengine to fix build failure

- mnemosyne/web_server/web_server.py
I currently host a Mnemosyne web-server instance on a remote server. To integrate it with other tools, I was an endpoint for the web server that reports the current number of scheduled cards. This PR adds an endpoint for getting the count of scheduled cards along with endpoints for non-memorized and active cards.
> Add scheduled card count apis

- mnemosyne/web_server/review_wdgt.py
Updates the web server to automatically resize images that are too large for the screen and to hide empty question/answer boxes. Hiding the empty answer boxes is especially useful for map cards that show both the question and answer as the question.
If either of the changes aren't acceptable to you, I'd be happy to remove that part from the MR.
> Improve web interface

- mnemosyne/web_server/review_wdgt.py
Resolves the issue mentioned in https://github.com/mnemosyne-proj/mnemosyne/issues/228. Previous images would be resized to always take up the entire screen width, but this had poor results with some small images, like LaTeX. This changes it to shrink images that are wider than the screen but not expand images that are smaller.
> Make images not grow to maximum size

- mnemosyne/pyqt_ui/about_dlg.py
- mnemosyne/pyqt_ui/getting_started_dlg.py
- mnemosyne/pyqt_ui/main_wdgt.ui
- mnemosyne/pyqt_ui/mnemosyne
- mnemosyne/pyqt_ui/tip_dlg.py
The reason for the problem is that the icon paths were not tied to the script, but to the current working directory.
Fix #234
> Fix a bug causing the app to not find its icons.

- mnemosyne/pyqt_ui/statistics_dlg.py
The combobox on a statistics page wasn't set to the correct index when the last shown variant of that page wasn't the first one in the list of combobox items.
Steps to reproduce:
1) Open the statistics widget and choose a variant which isn't the first one in the combobox list.
2) Close and reopen the statistics widget.
Expected result: The chart and combobox text will show the variant that was displayed before the widget was closed.
Actual behaviour: The correct chart is shown, but the combobox shows the text for the first item in the list.
> Initialize combobox with stored variant index in statistics widget

- setup.py
Fill some directive values to InnoSetup script to help Windows better display the app information.
For example, in Windows 11 settings "Installed apps" page, Mnemosyne only show its name with version in it, without publisher information and custom icon.
Compared with other app like InnoSetup itself:
Also, other app management software like WinGet also fails to determine the installed Mnemosyne's version:
> Enrich InnoSetup info for Windows installer

- mnemosyne/pyqt_ui/main_wdgt.py
Fixes #290. Handle a Ctrl-Q keypress that reaches the main widget by closing the application. Note that this means that the Ctrl-Q quit isn't active when dialogs are open, which I think is the right behavior.
> pyqt_ui: quit application when receiving ctrl-q

- mnemosyne/pyqt_ui/main_wdgt.py
- mnemosyne/pyqt_ui/main_wdgt.ui
I realized that this is a better way to make the change, and it displays the keybinding in the UI which is much more discoverable.
Follow up to #291
> pyqt_ui: Quit using Ctrl-Q using the .ui file rather than code

- mnemosyne/pyqt_ui/mnemosyne
This fixes the following runtime warning introduced in Qt 6.5.2:
QGuiApplication::setDesktopFileName: the specified desktop file name ends with .desktop. For compatibility reasons, the .desktop suffix will be removed. Please specify a desktop file name without .desktop suffix
> Fix desktop file name warning
